### ISSUE TITLE
Switch PRNGkey to required input?

### ISSUE THREAD

**Issue by tbmiller-astro** [pysersic/pysersic#48]
Each of the `sample` or `estimate_posterior` methods requires a PRNGKey so currently we have it as an optional with a default. I'm thinking though we maybe should have it be a required input so users (and me) use different keys for different runs leading to more robust results.

**Comment by prappleizer** [comment]
Not a bad idea. I mean, any user who didn't want to deal with it (or was only doing "one" run) could just set a variable at the top of their script/notebook and feed it in, but it would prevent anyone who was actually doing multiple runs from mistakenly thinking they were getting independent samples when they aren't. 

Another option would be to give `pysersic` the ability to randomize the PRNGKey at the start of the function. So you could make the PRNGKey default = "generate", in which `pysersic` would pick a random seed to use as the random seed, so to speak. Or you could set it directly. Or you could set it to "fixed" and `pysersic` will just have a single default (like 3) that it uses, in order to maintain some comparative alignment with docs or examples? 

I'm pretty fine either way!

**Comment by prappleizer** [comment]
Any further thoughts on this @tbmiller-astro ? Would like to implement and close if possible!

**Comment by tbmiller-astro** [comment]
Added in commit dca662913978b1a6b7182ad413d7b9b38051da4e
