### ISSUE TITLE
Question about best fit r_eff

### ISSUE THREAD

**Issue by ke27whal** [pysersic/pysersic#57]
Hi, 

I've been starting to play around with pysersic to measure the sizes of compact galaxies, and I have two questions about the parameter, r_eff.

1. Is the best fit value of r_eff the effective radius of the base sersic profile before it has been convolved with the PSF?
2. How does one interpret best fit r_eff values that are smaller than the FWHM of the PSF?

Thank you so much!

Best,
Kelly

**Comment by prappleizer** [comment]
Hi @ke27whal! 

Yes, `pysersic` forward models the galaxies, so it generates an intrinsic galaxy model using a set of properties (including reff) and then convolves this with the input psf before comparing to the data. When the posterior estimation / sampling results return an, e.g., 50th percentile r_eff smaller than the PSF FWHM, this is possible because the values are pre-convolution. 

To answer your second question, it definitely depends a bit. Reff is a parameter of a model being fit to all light pixels, so if the galaxy is "well resolved" out to beyond the PSF FWHM, then it is probably fine even if Reff itself is smaller than the PSF. But the smaller Reff gets with respect to the psf, the better you need to know the psf to say anything about whether the source is resolved or not. It's not cut and dry because different sersic indices will put different fractions of the light inside, and outside, of the PSF FWHM. 

I think the simplest approach is probably to fit such sources with the PSF itself as well as with a galaxy model. If the light distribution seen can be roughly as well modeled by just a PSF, then the galaxy is likely unresolved and its not well-motivated to attempt an extraction of sersic parameters. Conversely if the galaxy fit is considerably better than a PSF-only fit, that's an indication that the information is present to distinguish the galaxy as resolved.  


Cheers, 
Imad

**Comment by ke27whal** [comment]
Great, thank you so much!
